ngageoint/hootenanny-rpms

BuildArchive.sh
Refs ngageoint/hootenanny#472
Remove first hoot make because it isn't necessary in the RPM building process here.  Will be done later when the hoot binary RPM is built.
=> Removed hoot make

Makefile
1. refs https://github.com/ngageoint/hootenanny-rpms/issues/67
=> Omit OsmApiDb tests from RPM test VM

Makefile, src/SPECS/hootenanny.spec.in
References issue #102.
In the future it would be good to figure out how to get these excludes passing, but this should get us back and building for now.
=> Update excludes for new Frechet tests 102

src/Makefile, src/SPECS/FileGDB_API.spec
Refs ngageoint/hootenanny#1335
Updated the FileGDB API RPM to use the latest version, v1.4
The latest tar.gz extracts to FileGDB_API-64 vice FileGDB_API as before. So it is easier to create the directory and then strip the directory name from the tar extraction.
=> Upgrade FileGDB_API RPM from v1.3 to v1.4

src/SPECS/hootenanny.spec.in
Refs #138 
Hootenanny RPM build now requires aclocal, autoconf, autoheader, and automake before building due to recent Hootenanny repo changes.
=> Recent Hoot changes cause 'missing' failure

BuildArchive.sh, src/SOURCES/tomcat8.conf, src/SPECS/hootenanny.spec.in, src/SPECS/tomcat8.spec
References #144.
There was some references I missed the first round.  It still worked before because of jdk_111 being cached in the git working directory.  Once it's removed, then build failures happen.
This is a little out of the normal workflow since we are mid release.  I'd like to go straight into master then merge it into develop.
=> Fix jdk requires to latest release

Makefile, SPECS/hootenanny.spec, shell/BuildHoot.sh
This fixes various errata with `hootenanny.spec` related to dependency churn since the 0.2.38 release:
* 71c1f3f: Disable installing the `node-mapnik-server` code and service until it's fixed, see ngageoint/hootenanny#2111.  This prevented building of the Hootenanny RPM completely.
* 75b9545: Add `HOOT_HOME` environment variable to the `node-export` unit file, see ngageoint/hootenanny#2151.
* 600b504: Lock Hootenanny RPMs to explicitly require the exact GEOS version, complements 3.6.2 upgrade in ngageoint/hootenanny#2176.
=> Hootenanny Spec Fixes

README.md, SPECS/tomcat8.spec, config.yml, doc/verify.md
* Upgrades our Tomcat RPM to 8.5.28.
* Add documentation for verifying some of our upstream dependency sources.
=> Tomcat 8.5.28

Vagrantfile, config.yml, doc/maven.md, shell/Vars.sh
Fixes #177 by having Vagrant and the shell scripts download a tar archive containing a `repository` that is preseeded with Hootenanny services Java dependencies.
Additional fixes:
7c50b9b: Create `RPMS` folder as invoking user in `run_hoot_build_image` function; an error that @Cellington1 was probably encountering.
b80ec97: Look for `rpmbuild` instead of `rpm` and improve error message.
=> Maven Cache and Bugfixes

SPECS/hootenanny.spec
Fixes #179.  
RPM upgrades weren't working because during the `%pre` script section of the `hootenanny-services-ui` package the expanded contents of `hoot-services.war` were forcibly removed, and by the time either `updateConfigFiles` or `updateLiquibase` functions were executed, the `tomcat8` service would still be in the process of expanding the upgraded war.  This manifested in a variety of different errors, typically about missing database changeset files (for `updateLiquibase`) or missing properties files when calling `sed` (for `updateConfigFiles`).
The solution was to create a new function, `startTomcat` that would start the `tomcat8` service and wait for the all of the war files to be extracted before returning.  The function would query the systemd log since the time of service …
=> Fix RPM Upgrades

SPECS/hootenanny.spec
Companion PR to ngageoint/hootenanny#2283, removes the `report` directory from `hootenanny.spec`.
=> Remove report directory from RPM

SPECS/hootenanny.spec, Vagrantfile
Fixes #182 by only locking to the major and minor versions defined in `tomcat_version`.  Currently, this means the `hootenanny-services-ui` RPM can use the latest 8.5 version.
=> Loosen Tomcat Version Requirements

Vagrantfile, shell/Vars.sh
Fixes regressions introduced from #184, specifically it was necessary to add in a dummy `tomcat_version` define in the `spec_requires()` shell function (like what was done in the `Vagrantfile`).
=> Fix Regressions from 184

.dockerignore, Makefile, docker/Dockerfile.rpmbuild-repo, scripts/keepnewer.py, scripts/repo-sync.sh, shell/Vars.sh
This PR adds the ability to synchronize with a `yum` repository in a remote S3 bucket with the `repo-sync.sh` script.
* Files that are newer locally are kept (e.g., so Jenkins rebuilds are actually updated) using the `keepnewer.py` Python module; it's an `awscli` plugin that adds the logic and CLI option for `aws s3 sync --keep-newer`.
* Modify `hootenanny/rpmbuild-repo` container to include latest `awscli` (installed via `pip`) and add optional `role_arn` argument that can be used for including a role-based `awscli` configuration profile in the container (with credentials passed via environment, and not kept in container).
* Minor tweaks to the `Makefile`, including adding the `latest-archive` convenience target to produce the latest Hootenanny archive.
=> S3 Repository Sync

README.md, Vagrantfile
Fixes #188.  Documents that Vagrant 2.0 is required and enforces it in the `Vagrantfile`.  Also update the `Makefile` targets and remove an outdated note from the `README`.
=> Require Vagrant 2.0

Makefile
Fixes #191 by:
* Requiring `BUILD_IMAGE` for archive creation.
* Automatically setting `GIT_COMMIT` when `HOOT_VERSION_GEN` is specified for archive creation.
=> Fix Makefile Errors

scripts/hoot-archive.sh
Fixes #195.  This adapts to the `hoot-archive.sh` script to use the canonical archiving script from the Hootenanny repository from ngageoint/hootenanny#2393.  If the Hootenanny revision doesn't have the script, it falls back to its old behavior (to be removed when no longer necessary).
=> Use Hootenanny Archive Script

docker/Dockerfile.rpmbuild-base, docker/Dockerfile.rpmbuild-gdal, docker/Dockerfile.rpmbuild-generic, docker/Dockerfile.rpmbuild-hoot-devel, docker/Dockerfile.rpmbuild-hoot-release, docker/Dockerfile.rpmbuild-pgdg, docker/Dockerfile.rpmbuild-postgis, docker/Dockerfile.rpmbuild-repo, docker/Dockerfile.run, docker/Dockerfile.run-base, docker/Dockerfile.run-base-devel, docker/Dockerfile.run-base-release
This PR adds `yum -q -y clean all` once all RPM installation is complete in the containers; doing so saves space on image size.
=> Yum Cleanup

Makefile, config.yml, docker/Dockerfile.rpmbuild-check, docker/Dockerfile.rpmbuild-lint, shell/Vars.sh
This adds the `rpmbuild-lint` container that has `yamllint` and `shellcheck` installed.
=> rpmbuild-lint

Makefile, config.yml, shell/Vars.sh
Fixes a longstanding TODO: the distribution ("dist") part of the package string should come from the value in `config.yml` rather than being hardcoded.
=> Retrieve RPMBUILD_DIST from configuration file

README.md, Vagrantfile, doc/config.md
This PR will use the same UID of invoking user for `rpmbuild` in containers if the `RPMBUILD_UID_MATCH` environment variable is set.  In addition, configuration documentation was added for the environment variable, `MAVEN_CACHE` (#178), and `config.yml`.
=> Match UID for rpmbuild

docker/Dockerfile.rpmbuild-generic, docker/Dockerfile.rpmbuild-hoot-release
As it says in the title, move the changes from #207 up to a base container so it applies everywhere (in particular to `rpmbuild-hoot-release`).
=> Move git configuration up to the rpmbuild-container.

.circleci/config.yml
Enables CircleCI for tests; this will replace the the defunct Jenkins test suite we have.  Currently this suite will:
* Lint the YAML and shell scripts.
* Build the `rpmbuild-hoot-release` container (the most important)
Additional tests, including the `develop` repository job, will come in later PRs.
=> Add CircleCI configuration for tests.

Vagrantfile, config.yml, docker/Dockerfile.rpmbuild, shell/Vars.sh
Correct branch destination now.
By default, `useradd` gives the new user a primary group with a GID matching the UID; customization of the GID is not supported.  This PR enables customization of the GID, this is necessary to support CircleCI's build user (`circleci`), whose values don't match.  Due to [bind mounts](https://docs.docker.com/storage/bind-mounts/), both must match the invoking user or else there will be file permission issues writing RPMs.
=> rpmbuild gid build argument

.circleci/config.yml, scripts/latest-archive.sh, scripts/query-archive.sh, scripts/repo-sync.sh, scripts/rpm-install.sh, tests/lint-bash.sh
This PR enables an RPM pipeline that takes Hootenanny `develop` archives generated on by that repository's tests (added in ngageoint/hootenanny#2445), compiles RPMs from the archive, and updates the `develop` repository with the compiled RPMs.  An RPM won't be created if one already exists in the repository (it takes ~30 minutes to compile an RPM on the free CircleCI instance).
Some notes:
* A separate CircleCI workflow, `develop-repo`, is used so that it can be [triggered on a set schedule](https://circleci.com/docs/2.0/configuration-reference/#schedule)
* Determining the latest archive and if querying if that archive's git commit is already a part of the RPM in the repo are handled by the added `latest-archive.sh` and `query-archive.sh` scripts, respectively.  These are essentially just …
=> Develop Repository Pipeline

.circleci/config.yml, scripts/repo-sync.sh, scripts/slack-notify.sh, scripts/vagrant-install.sh, tests/lint-bash.sh
This enables Slack notifications upon updates to the `develop` RPM repository.  It uses the added `scripts/slack-notify.sh` script using the release information from the autostart RPM package.
Additional changes:
* Remove AWS profile usage by default in `repo-sync.sh` (a747682).
* Upgrade to Vagrant 2.1.2 (2b8b5b5).
=> Slack Notifications

tests/update-sync-repo.sh
During testing of #221 I disabled slack notifications and missed that I didn't include the setting of `$RPM_VERSION`.  I'm bringing it back here, otherwise the script will fail after sync and there'll be no slack message (due to `set -u`).  In addition, I used `find` instead of `ls` because `shellcheck` will fail otherwise with:
> SC2012: Use find instead of ls to better handle non-alphanumeric filenames.
=> RPM_VERSION hotfix

.circleci/config.yml, tests/install-test-rpm.sh
This PR adds a new testing script, `test-rpm-install.sh`, that tests installing the created RPMs prior to syncing with our repository in S3.  I also added the capability to run Hootenanny unit tests, but the CircleCI testing containers would be consistently killed; paring down to just the "quick" tests was even too much.  Thus, the functionality of the RPMs (can they be installed) is tested, but the running the unit tests has to be punted to until more memory is available or creating a separate Jenkins pipeline.
=> Test RPM Installation

SPECS/tomcat8.spec, config.yml
This upgrades the `tomcat8` package to 8.5.34.  A signed candidate package is available in S3, and may be used with the following Yum repo configuration:
```
[hoot-deps]
name = Hootenanny Dependencies
baseurl = https://s3.amazonaws.com/hoot-repo/el7/deps/upgrade
enabled = 1
gpgcheck = 1
repo_gpgcheck = 1
gpgkey = https://s3.amazonaws.com/hoot-repo/el7/hoot.gpg
```
=> Tomcat 8.5.34

SPECS/hootenanny.spec
This removes `pwgen` (sourced from EPEL) as a requirement and uses a Python snippet to generate a random password instead.  The snippet leverages Python's [`SystemRandom`](https://docs.python.org/2/library/random.html#random.SystemRandom) module to ensure that a cryptographically secure pseudo-random source is used.
=> pwgen removal

SPECS/hoot-postgis24.spec, config.yml
This fixes some packaging issues with the PostGIS 2.4.4-1 release, most importantly fixing to allow the latest Hootenanny release to install again.  Specifically, `hootenanny-services-ui` had a hard dependency on the `hoot-postgis23_95` package, which was obsoleted by the 2.4.4-1 release with #230.  The key was to have the `hoot-postgis24_95` package also *provide* the capabilities of the `hoot-postgis23_95` package it obsoletes, allowing the old Hootenanny releases to resolve the dependencies again.
In addition, previous version symlinks for the raster and topology shared libraries were added to smooth over compatibility issues for existing PostGIS 2.3 databases.  Prior to this, using some spatial functions could cause errors:
```
wfsstoredb=# SELECT postgis_full_version();
ERROR:  could …
```
=> PostGIS 2.4 Hotfix

SPECS/hootenanny.spec, Vagrantfile, scripts/hoot-checkout.sh, scripts/nodejs-install.sh, scripts/nodesource-repo.sh, tests/lint-bash.sh
This PR includes the Hootenanny UI 2.0 files in the RPM, available at `/hootenanny-id2x`.  This adds a binary condition, `hoot_ui2`, set by default to `hootenanny.spec`.
The following minor changes are also included:
* `node_mapnik` binary condition now used (unset by default) instead of `with_node_mapnik` global
* Can add `with` / `without` settings to `config.yml` for use in building RPMs.
* Fix quoting in a few shell scripts to be up to `shellcheck`'s standards.
=> Include Hootenanny UI 2.0 Files

scripts/vagrant-install.sh
Use Vagrant 2.2.0, released 10/16/2018.
=> Upgrade to Vagrant 2.2.0.

SPECS/hootenanny.spec, scripts/runtime-entrypoint.sh
With the merge of ngageoint/hootenanny#2700 there's no need to keep around the conditionals and code for the `node-mapnik` service.
=> Remove node-mapnik

SPECS/hootenanny.spec
This PR adds an optional `rpmbuild` conditional, `hoot_db`, that allows creation of a `hootenanny-db` package.   The package includes files necessary to re-create the Hootenanny database schema without requiring all of the runtime baggage:
* Liquibase changesets that comprise the services database schema.
* `blank_osmapidb.sh.in` template for creating the OSM API database.
Due to the nature of database schema changes, it's not necessary to build this RPM often, hence why it's also placed in the dependency repository.
=> Add optional hootenanny-db package

config.yml
This updates the Maven cache for the latest in develop ([ngageoint/hootenanny@8e02eb2](https://github.com/ngageoint/hootenanny/blob/8e02eb2a4dc9a180e7bca62645b88f0da7371c0a/hoot-services/pom.xml)).  Here's a [difference from the `m2-cache-2018-10-02.tar.gz` archive](https://gist.github.com/jbronn/10a82638fb5722ef7f5221fea669b60a) for further reference.
=> Maven Cache Refresh

.circleci/config.yml, SPECS/hootenanny.spec, scripts/vagrant-install.sh
This PR adds `libpng-devel` to the packages required to build Hootenanny, necessary from changes introduced with ngageoint/hootenanny#2829.  I then pushed up container images with the new dependency, which should fix our `develop` RPM workflow.
=> libpng required

SPECS/hoot-words.spec
This modifies `hoot-words.spec` to get its source from the `s3://hoot-support` bucket.
=> Use hoot-support bucket

.circleci/config.yml, SPECS/hootenanny.spec
Fixes #252.  Uses Qt5 instead of Qt4 in the build images.  *Do not merge* until ngageoint/hootenanny#3035 is complete, otherwise our RPM builds will fail due to Qt conflicts.
=> Upgrade to Qt5

SPECS/hootenanny.spec
In #253 I forgot to change the `Requires` tags to use Qt5 packages making it impossible to test #254.
=> Use Qt5 packages in requirements.

.circleci/config.yml, docker/Dockerfile.run-base
Update the image references for the latest version from Docker Hub; rebuilt due to #260, ensuring that qt4 is purged.  In addition, qt5 packages were replaced for our runtime base image.
=> CircleCI Image Updates

.circleci/config.yml, SPECS/hootenanny.spec
Fixes #264: remove `logc4xx` and `logc4xx-devel` from RPM requirements and update hashes to latest Docker images.
=> Remove logc4xx

Makefile, SOURCES/armadillo-tests-makefile.patch, SPECS/armadillo.spec, Vagrantfile, config.yml, docs/provenance.md, shell/BuildDeps.sh, shell/Vars.sh
Allows us to vendor the `armadillo` RPM; using the latest release of 9.400.3, which should match what they'll use in EPEL 8.
=> Armadillo 9.400.3

SPECS/hootenanny.spec
the pg_dotless variable was mixed up, causing the pgdata directory to not be populated. This made the spec file fall into a loop waiting for postgresql to start with it never being possible. This commit is to fix the jenkins pipeline 'hootenanny-rpms'
=> update pg_dotless to initialize the database

SPECS/hootenanny.spec, config.yml, docker/Dockerfile.rpmbuild-hoot-devel, docker/Dockerfile.run-base-devel, scripts/hoot-db-setup.sh
Fixes #228; companion to ngageoint/hootenanny#3319.   Removes PostGIS as a buildtime and runtime requirement of the Hootenanny RPM.   Further removal of source archives, spec files, and Docker files will be handled in #277.
=> Remove PostGIS dependency and WFS References

SPECS/dumb-init.spec
Upgrades `dumb-init` to 1.2.2 and improvements to the spec file:
* Use standard compilation and hardening flags like we do on rest of the RPMS (by using `sed` on the `Makefile` to allow override of the `CFLAGS`)
*  Remove deprecated metadata and fix nits in the description
* Include documentation files in RPM
=> dumb-init 1.2.2

.circleci/config.yml, docker/Dockerfile.rpmbuild-base
Companion to ngageoint/hootenanny#3624: adds `parallel` to the `rpmbuild-base` image and updates the CircleCI images to the latest releases.
=> Parallel Container

README.md, docs/setup.md
Added documentation about how GNU Awk is required.  This is necessary now since Ubuntu 18.04+ has been shipping without using it as the default `awk` implementation.
=> GNU Awk Documentation

scripts/repo-sign.sh
I reviewed our processes due to [sha-mbles](https://sha-mbles.github.io), and while we are signing our RPMs properly we were using GnuPG defaults for the repository metadata.  Unfortunately, the GnuPG defaults are SHA-1 which is insecure; this PR changes us to use SHA512 instead.
=> Repository Digest Algorithm Upgrade

.circleci/config.yml, SPECS/nodejs.spec, config.yml
Creates a new release of NodeJS:
* Explicitly remove the `http_parser` from its bundled dependencies, forcing use of the `http-parser` shared library from CentOS.  This should fix issues with installing Mocha and accepting POST data due to updates that fixed [CVE-2019-15605](https://access.redhat.com/security/cve/cve-2019-15605).
* Upgrade NPM to 6.4.14.
* Remove debug compilation flags and update CircleCI images.
The updated RPM has been uploaded to our release dependency repository, and Docker images have been updated to include it.
=> NodeJS 8.9.3-2

.circleci/config.yml
This will allow hoot-testing to update it's rpm before anyone starts work in EST timezone, and the rpm update won't interrupt any running jobs in progress.
fixes #303
=> Push first rpm build back to 0800 UTC

shell/Vars.sh
The `config.yml` file changed from `dumbinit` to `dumb-init` and was causing the build to fail.  This fixes the failure.
=> Fix CircleCI failure for RPM build

docs/provenance.md, shell/Vars.sh
* Remove unused variables from `shell/Vars.sh` that were preventing the RPM build.
* Update some the provenance documentation since we added `lcov`.
=> GEOINT Cleanup

Makefile, docs/release.md, shell/BuildHoot.sh
The [latest RPM issue](https://app.circleci.com/pipelines/github/ngageoint/hootenanny-rpms/1057/workflows/4191bc8d-fe93-4e24-a3f6-85bdd25eeb45/jobs/9265) is that we removed the definitions for the `{gdal,geos}_version` variables.  Although we no longer build GEOS/GDAL in this repo, we still need to pass in the versions to Hoot's spec file.
=> Define GEOS/GDAL Version Variables Again

SPECS/hootenanny.spec
Allows `hoot-tests` to access `hoot-josm`
=> Enable test output validation

SPECS/hootenanny.spec
fixes this error after JOSM validation was integrated.
>hoot version
/usr/bin/hoot.bin: error while loading shared libraries: libjvm.so: cannot open shared object file: No such file or directory
=> set JAVA_HOME (and create a new userfiles "changesets" folder)

.circleci/config.yml
so that nightly box can rpm update won't miss the latest build.
=> Move morning rpm cron job to 0600 UTC (0100 EST)

SPECS/nodejs.spec, config.yml
Fixes #332.  Lock `npm` version along with `nodejs` release.  This will allow our existing releases of Hootenanny to work (as they're locked to NodeJS 14.16.1) but they'll get a release that won't try and install `npm` 8.
=> Update NodeJS to lock with NPM version.

SPECS/nodejs.spec, Vagrantfile, config.yml, docker/Dockerfile.rpmbuild-hoot-release, scripts/nodejs-install.sh
Explicitly define `v8-devel` version and lock it like we do with NodeJS.
=> Lock v8-devel version

.circleci/config.yml, Makefile, SPECS/hootenanny.spec, SPECS/nodejs.spec, Vagrantfile, config.yml, docker/Dockerfile.run-base, docker/Dockerfile.run-base-release, shell/BuildHoot.sh
* Track all NodeJS bundled versions in configuration like done with v8.
* Lock `v8-devel` version for `core-devel-deps`.
* Exclude `/usr/bin/node` from generating automatic requirements.
* Fix v8 issues with the runtime containers (uses in RPM tests).
=> NodeJS Bundled Versions / Hootenanny Spec Fixes

SPECS/libphonenumber.spec, config.yml
* Links to upgraded `protobuf` 3.17 from radiant-maxar/geoint-deps#45 (major version of the library changed).
* Updates build to use CMake 3.
=> Upgrade libphonenumber to 8.12.52

.circleci/config.yml, Makefile, docker/Dockerfile.rpmbuild-pgdg, scripts/geoint-repo.sh, scripts/pgdg-repo.sh
* Respect `HOOT_RELEASE` environment variable so it's possible to create an iteration release, e.g. for `0.2.72-2`:
```
HOOT_RELEASE=2 HOOT_VERSION_GEN=0.2.72 make rpm
```
* Update CircleCI images to latest versions.
* Updates to `pgdg-repo.sh` (check metadata signatures, support testing repository) and `geoint-deps.sh` (EL9, make repo name cache friendly).
* Minor cleanup of `Dockerfile.rpmbuild-pgdg`
=> Hoot Release Fix & CircleCI Image Updates

SOURCES/libpostal-configure.patch, SPECS/libpostal.spec, config.yml
LibPostal's latest release is a bit different than prior releases.  The source code location is different and the name of the tar file is non-standard.  The parser, classifier, and data source code tar files weren't updated at all for this release and weren't included in the release so they had to come from the prior release.  There were also changes in the test Makefile that required an updated patch.
=> Upgrade LibPostal from v1.0.0 to v1.1

scripts/rpm-install.sh
Was previously getting this error on Ubuntu 20.04 when running `./scripts/rpm-install.sh`
```
W: GPG error: https://ubuntugis.qgis.org/ubuntugis focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D155B8E6A419C5BE
E: The repository 'https://qgis.org/ubuntugis focal InRelease' is not signed.
```
https://askubuntu.com/questions/13065/how-do-i-fix-the-gpg-error-no-pubkey
=> get ubuntu key
