.gitattributes
static/words1.sqlite.bz2

Refs #6 
Added the .bz2 file that can be downloaded for the RPM build and also for the main Hootenanny build

Adding words1.sqlite.bz2 into static folder

---

Makefile

Add npm install to deps

---

Makefile

1. refs https://github.com/ngageoint/hootenanny-rpms/issues/23

Remove geos/gdal before installing deps

---

BuildArchive.sh
Makefile

1. refs #27
2. Also, pull submodules.

Remove tmp/hootenanny in clean-all

---

src/SPECS/hootenanny.spec.in

Enabled ConflationStatsReportTest in RPM build

---

src/SPECS/hootenanny.spec.in

restore rpm saved db config file if present

---

src/Makefile

1. refs https://github.com/ngageoint/hootenanny-rpms/issues/62

Add retry to autoconf build.

---

Makefile
src/SPECS/hootenanny.spec.in

1. refs https://github.com/ngageoint/hootenanny-rpms/issues/65

Add ConflateAverageTest.sh to exclude list.

---

BuildArchive.sh
src/SPECS/hootenanny.spec.in

Refs ngageoint/hootenanny#746
Updated RPM build to work with both versions of `conf/DatabaseConfig.sh.orig` and `conf/DatabaseConfigDefault.sh`

Rework the DatabaseConfig.sh structure

---

src/SPECS/hootenanny.spec.in

Swapped spring-database.xml for db.properties

---

src/SPECS/hootenanny.spec.in

Fixed typo in dB password modification

---

src/SPECS/hootenanny.spec.in

add renderdb-export-server to rpm install

---

src/SPECS/hootenanny.spec.in

tomcat user doesn't have write permission to files in /etc/tomcat6

---

src/SPECS/hootenanny.spec.in

wait for pg to start

---

src/SPECS/hootenanny.spec.in

services rpm no longer backs up and restores postgres and tomcat configs

---

Vagrantfile
fix_postgres.sh
src/Makefile
src/SPECS/gdal.spec
test/Vagrantfile

1. refs #114 
Added an Epoch to the RPM and a bit of cleanup.

Added an Epoch to the GDAL rpm

---

src/SPECS/gdal.spec

Enabled Java bindings and updated tabulation, etc.

Enable Java bindings in GDAL RPM

---

BuildArchive.sh
src/SPECS/hootenanny.spec.in

Check for and correct previous install of db config

---

BuildArchive.sh
src/SPECS/hootenanny.spec.in

Add symbolic link for gdal2tile to fix bad reference

---

src/SPECS/hootenanny.spec.in

Fix allow linking for CentOS6.7

---

.gitignore
BuildArchive.sh
Makefile
VagrantfileLocal.vbox
src/Makefile
src/SPECS/FileGDB_API.spec

Esri repo changed structure so our vagrant builds that download the source zip aren't functioning correctly. This change was part of the v1.5 release. So I'm going to upgrade from v1.4 to v1.5 while I'm at it.

Fix FGDB build

---

Makefile
update-repo/Vagrantfile
update-repo/VagrantfileLocal.vbox

Added code to update the RPM repo in a tiny VM

---

src/SPECS/hootenanny.spec.in

This pull request stems from https://github.com/ngageoint/hootenanny/issues/753 ('Consolidate hoot-services writeable directories to a single location')

Services' directory consolidation

---

BuildArchive.sh
Makefile
fix_postgres.sh
src/SPECS/hootenanny.spec.in
test/Vagrantfile

Fix typos etc

---

.gitignore
Makefile
src/SPECS/hootenanny.spec.in

Let's go with the latest release of java for now and see how it works.  Longer term we can find a different solution.
References #144 and #146

Updates for latest release of java

---

src/SPECS/hootenanny.spec.in

only install production deps

---

repos/HootBuild.repo

Doesn't look like this repo is maintained anymore. Refs #163

Disable kde repo.

---

README.md

Updating to include instructions on how to install from public repo.

---

src/SPECS/hootenanny.spec.in

update rpm spec to deploy UI dist files

---

docker/Dockerfile.rpmbuild
docker/Dockerfile.run-base

Eliminates unnecessary intermediate image layers (they'll still be huge).

Consolidate ENV Statements in Dockerfiles

---

Makefile

Fix More Makefile Errors

---

Vagrantfile

Use `Vagrant::Util::Subprocess` instead of backticks for more robust execution of `rpmspec` command in the `Vagrantfile`.

Use Vagrant Subprocess Module

---

.yamllint
scripts/nodesource-repo.sh
scripts/repo-update.sh
tests/README.md
tests/lint-bash.sh
tests/lint-yaml.sh

This PR adds linting tests for checking the basic validity and quality of YAML and bash scripts.

Lint Tests

---

config.yml

As it says in the title, upgrade the Tomcat package to 8.5.32; new source tarball was GPG verified.

Upgrade to Tomcat 8.5.32.

---

scripts/vagrant-install.sh

As it says, just use the latest Vagrant release.

Upgrade to Vagrant 2.1.4.

---

.circleci/config.yml

Update to the latest releases in the CircleCI configuration.

Container Updates

---

config.yml

Use a file with updated cached dependencies for Maven.

Refresh Maven Cache

---

SPECS/hootenanny.spec

refs: #234 
NOTE: I'm not sure where the PDF files are getting installed. There is a docs tar archive and they are in the source archive.

Removed document packages

---

SPECS/hootenanny.spec

migrate UI deploy paths

---

SPECS/hootenanny.spec
docker/Dockerfile.rpmbuild-pgdg
scripts/pgdg-repo.sh

Add improvements to `pgdg-repo.sh`, `hootenanny.spec`, and `Dockerfile.rpmbuild-pgdg` to support PostgreSQL 10+.  Basically porting the same changes from ngageoint/hootenanny@699c5e2.

PostgreSQL 10+ Support

---

SPECS/tomcat8.spec
config.yml
docker/Dockerfile.rpmbuild
docker/Dockerfile.rpmbuild-base
docker/Dockerfile.rpmbuild-gdal
docker/Dockerfile.rpmbuild-generic
docker/Dockerfile.rpmbuild-hoot-devel
docker/Dockerfile.rpmbuild-hoot-release
docker/Dockerfile.rpmbuild-libgeotiff
docker/Dockerfile.rpmbuild-libpostal
docker/Dockerfile.rpmbuild-lint
docker/Dockerfile.rpmbuild-pgdg
docker/Dockerfile.rpmbuild-postgis
docker/Dockerfile.rpmbuild-repo
docker/Dockerfile.rpmbuild-sonarqube
docker/Dockerfile.run
docker/Dockerfile.run-base
docker/Dockerfile.run-base-devel
docker/Dockerfile.run-base-release
scripts/vagrant-install.sh

* Upgrade Tomcat to 8.5.43
* Update copyright notices and label metadata in the Dockerfiles
* Upgrade Vagrant version to 2.2.5

Tomcat 8.5.43

---

.circleci/config.yml
Makefile
README.md
docs/install.md
docs/tests.md
scripts/hoot-checkout.sh
scripts/repo-sync.sh
shell/BuildArchive.sh
tests/create-rpm.sh
tests/update-sync-repo.sh
tests/upgrade-rpm.sh
tests/yum-configure.sh

changes to move forward with trunk based development, for the Hootenanny repository

Trunk transition

---

.circleci/config.yml
Makefile
README.md
docs/install.md
docs/tests.md
scripts/hoot-checkout.sh
scripts/repo-sync.sh
shell/BuildArchive.sh
tests/create-rpm.sh
tests/update-sync-repo.sh
tests/upgrade-rpm.sh
tests/yum-configure.sh

* updates for hoot trunk based dev
* update markdown files and update scripts that were found to default with the develop branch

Trunk transition (#287)

---

SPECS/tomcat8.spec
config.yml
docs/verify.md

Upgrade to Tomcat 8.5.51 and fix some documentation links.

Tomcat 8.5.51

---

Vagrantfile_RPM_Test
scripts/jenkins/Jenkinsfile

task in association to jira ticket: https://radiantsolutions.atlassian.net/browse/VGI-1659

add tagging for ec2 instances started by Jenkins jobs

---

scripts/jenkins/Jenkinsfile

Noticed nproc was changed to 6, made same change for hootenanny-rpms jenkins job

update with static workers

---

SPECS/tomcat8.spec
config.yml

Upgrade to 8.5.64, [hot off the presses](https://ci.apache.org/projects/tomcat/tomcat85/docs/changelog.html).

Upgrade Tomcat to 8.5.64.

---

docs/install.md

Added info that CentOS7 is required.

Added info that CentOS7 is required.

---

SPECS/hootenanny.spec

include hoot-josm dependencies in rpm

---

SPECS/tomcat8.spec
config.yml

Upgrade to the latest Tomcat [8.5 release](https://tomcat.apache.org/tomcat-8.5-doc/changelog.html).

Upgrade Tomcat to 8.5.81
